"""
All of the Enums defined for the Cutscene Editor.
"""
from enum import Enum, auto


class EventDefinitionEnum(Enum):
    """
    An enum representing a given SubEvent.
    """
    moveToonsInBlock = auto()
    turnToonsToNode = auto()
    turnToonsToPoint = auto()
    moveSingleToon = auto()
    turnSingleToonToNode = auto()
    turnSingleToonToPoint = auto()
    turnSingleToonToHpr = auto()
    turnToonsToHpr = auto()
    tpToonsToElevator = auto()
    hideSuits = auto()
    showSuits = auto()
    moveCameraPosHpr = auto()
    moveCameraPos = auto()
    moveCameraHpr = auto()
    changeCameraFov = auto()
    reparentCamera = auto()
    reparentNode = auto()
    cameraToElevator = auto()
    actorDialogue = auto()
    actorDialogueIt = auto()
    showNametag = auto()
    hideNametag = auto()
    actorChat = auto()
    timeSleep = auto()
    turnActor = auto()
    moveActor = auto()
    particleSystemRun = auto()
    moveParticleSystemPos = auto()
    moveParticleSystemHpr = auto()
    nodePosHprScale = auto()
    hideSuit = auto()
    showSuit = auto()
    doSuitAnim = auto()
    doSuitBlendAnim = auto()
    doSuitHeadAnim = auto()
    doSuitPingpong = auto()
    suitApplyVisualEffect = auto()
    suitUnapplyVisualEffect = auto()
    moveToonsToBattlePos = auto()
    heavyDropKill = auto()
    animateSingleToon = auto()
    animateAllToons = auto()
    pingpongSingleToon = auto()
    pingpongAllToons = auto()
    actorShutUp = auto()
    showNode = auto()
    hideNode = auto()
    scaleNode = auto()
    scaleNodeList = auto()
    moveNode = auto()
    posRelativeToOther = auto()
    rotateNode = auto()
    animateAllSuits = auto()
    pingpongAllSuits = auto()
    disguiseAllToons = auto()
    undisguiseAllToons = auto()
    setAllAnimStates = auto()
    setOneAnimState = auto()
    clearAllSuitChat = auto()
    dyeParticleSystem = auto()
    toonFireFromCannon = auto()
    hideToons = auto()
    showToons = auto()
    hideToon = auto()
    showToon = auto()
    colorScaleNode = auto()
    alphaScaleNode = auto()
    setAllEmote = auto()
    setOneEmote = auto()
    suitSupaFly = auto()
    suitLockPropeller = auto()
    suitProjectileFly = auto()
    turnSuitsToNode = auto()
    turnSuitsToPoint = auto()
    turnSingleSuitToNode = auto()
    turnSingleSuitToPoint = auto()
    turnSingleSuitToHpr = auto()
    turnSuitsToHpr = auto()
    suitFireFromCannon = auto()
    playSoundEffect = auto()
    stopSoundEffect = auto()
    playMusic = auto()
    stopMusic = auto()
    functionCall = auto()
    functionLerp = auto()
    openElev = auto()
    closeElev = auto()
    laaTrapdoor = auto()
    showTimescaleChange = auto()
    applyStagelight = auto()
    setClearColorScale = auto()
    dustcloudNode = auto()
    doScreenFade = auto()
    showBoss = auto()
    hideBoss = auto()
    showBosses = auto()
    hideBosses = auto()
    doBossAnimation = auto()
    bossRollToPoint = auto()
    turnAndMoveToon = auto()
    createFog = auto()
    destroyFog = auto()
    setFogColor = auto()
    setFogDensity = auto()
    setToonExpression = auto()
    setToonSpecies = auto()
    suitColorScale = auto()
    createExplosion = auto()
    setToonEyes = auto()
    basicLabel = auto()
    colorNode = auto()
    fakeCannonControl = auto()
    squishToon = auto()
    jiggleNode = auto()


class SubEventArgumentType(Enum):
    """
    The different types of EventArguments.
    """
    slider_xyz = auto()
    slider_hpr = auto()
    slider_min_zero = auto()
    slider_min_almost_zero = auto()
    slider_float = auto()
    slider_xyz_camera = auto()
    slider_hpr_camera = auto()
    slider_fov = auto()
    textbox_str = auto()
    textbox_float = auto()
    dropdown_messages = auto()
    dropdown_actors = auto()
    dropdown_toons = auto()
    dropdown_suits = auto()
    dropdown_toon_anims = auto()
    dropdown_suit_anims = auto()
    dropdown_suit_head_anims = auto()
    dropdown_node = auto()
    dropdown_function = auto()
    dropdown_elevators = auto()
    dropdown_blendType = auto()
    dropdown_blockShape = auto()
    dropdown_particles = auto()
    dropdown_targetGroup = auto()
    dropdown_suitFlyChoice = auto()
    dropdown_suitFlyPosChoice = auto()
    dropdown_sound_effects = auto()
    dropdown_music = auto()
    dropdown_fogType = auto()
    dropdown_toonExpression = auto()
    dropdown_toonSpecies = auto()
    dropdown_toonEyes = auto()
    boolean = auto()
    slider_xyz_scale = auto()
    slider_xyz_node = auto()
    slider_hpr_node = auto()
    dropdown_toon_anim_states = auto()
    dropdown_arguments = auto()
    slider_rgb = auto()
    dropdown_toon_emote = auto()
    slider_hpr_toon = auto()
    slider_hpr_suit = auto()
    slider_hpr_cannon = auto()
    dropdown_bosses = auto()
    dropdown_boss_anims = auto()


class EventSequenceMode(Enum):
    """
    The type of sequence which an Event uses.
    """
    Sequence = auto()
    Parallel = auto()


class PauseFlags(Enum):
    """
    Reasons why the sequence is paused right now.
    """
    ChangingTime = auto()
    TimelineState = auto()
    PauseButton = auto()


class ToonBlockShape(Enum):
    """
    The shape of the block in which Toons should congregate (e.g. in seq_moveToonsInBlock()).
    """
    Elevator = auto()
    BigElevator = auto()
    SingleFile = auto()
    DoubleFile = auto()
    FourWide = auto()
    EightWide = auto()
    Line = auto()
    Circle = auto()


class ToonSubEventTargetGroup(Enum):
    """
    For Toon SubEvents, choice of whether the SubEvent should affect players, NPCs, or both.
    """
    All = auto()
    Players = auto()
    NPCs = auto()
